services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    image: aldofrotaa/concierge-api:v1.0
    container_name: api
    restart: always
    ports:
      - 50051:50051
      - 9989:9989
    volumes:
      - ./api:/usr/concierge/api
    environment:
      PORT: 9989
      PORT_GRPC: 50051
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb/concierge
      JWT_SECRET: w0pKf8zNjTg2VzUQX4YjKPttZ3bVXznX2iwZvVToRoE=

  app:
    build:
      context: ./app
    container_name: app
    # entrypoint: sh ./.docker/entrypoint.sh
    restart: always
    depends_on:
      - api
    ports:
      - 3000:8080
    # volumes:
    #   - ./app:/usr/concierge/app
    environment:
      API: "http://localhost:9989"
      KEY_ENCRIPTY: "concierge-app"

volumes:
  mongodb_data:
    driver: local
  cache:
    driver: local
